[build]
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."schedules/weekly-job"]
  schedule = "@weekly"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
